input {
  beats {
    port => 5044
  }
}

filter {
  date {
    match => ["status_timestamp", "UNIX"]
    target => "@timestamp"
    remove_field => ["status_timestamp"]
  }
  mutate {
    convert => {
      "temperature" => "float"
      "humidity" => "integer"
      "wind_speed" => "integer"
      "station_id" => "integer"
      "s_no" => "integer"
    }
    remove_field => ["weather"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]  # Docker service name
    index => "weather-stations-%{+YYYY.MM.dd}"
  }
}
